<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminUsersSessionInvalidateApplicationJSON
{
	#[\JMS\Serializer\Annotation\SerializedName('session_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $sessionId;
    
    /**
     * ID of the team that the session belongs to
     * 
     * @var string $teamId
     */
	#[\JMS\Serializer\Annotation\SerializedName('team_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $teamId;
    
	public function __construct()
	{
		$this->sessionId = 0;
		$this->teamId = "";
	}
}
