<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminUsergroupsAddTeamsApplicationJSON
{
    /**
     * When `true`, this method automatically creates new workspace accounts for the IDP group members.
     * 
     * @var ?bool $autoProvision
     */
	#[\JMS\Serializer\Annotation\SerializedName('auto_provision')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $autoProvision = null;
    
    /**
     * A comma separated list of encoded team (workspace) IDs. Each workspace *MUST* belong to the organization associated with the token.
     * 
     * @var string $teamIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('team_ids')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $teamIds;
    
    /**
     * An encoded usergroup (IDP Group) ID.
     * 
     * @var string $usergroupId
     */
	#[\JMS\Serializer\Annotation\SerializedName('usergroup_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $usergroupId;
    
	public function __construct()
	{
		$this->autoProvision = null;
		$this->teamIds = "";
		$this->usergroupId = "";
	}
}
