<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class AdminTeamsSettingsSetDefaultChannelsRequestBody
{
    /**
     * An array of channel IDs.
     * 
     * @var string $channelIds
     */
	#[SpeakeasyMetadata('form:name=channel_ids')]
    public string $channelIds;
    
    /**
     * ID for the workspace to set the default channel for.
     * 
     * @var string $teamId
     */
	#[SpeakeasyMetadata('form:name=team_id')]
    public string $teamId;
    
    /**
     * Authentication token. Requires scope: `admin.teams:write`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('form:name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->channelIds = "";
		$this->teamId = "";
		$this->token = "";
	}
}
