<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminUsersSetRegularApplicationJSON
{
    /**
     * The ID (`T1234`) of the workspace.
     * 
     * @var string $teamId
     */
	#[\JMS\Serializer\Annotation\SerializedName('team_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $teamId;
    
    /**
     * The ID of the user to designate as a regular user.
     * 
     * @var string $userId
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $userId;
    
	public function __construct()
	{
		$this->teamId = "";
		$this->userId = "";
	}
}
