<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminConversationsDisconnectSharedApplicationJSON
{
    /**
     * The channel to be disconnected from some workspaces.
     * 
     * @var string $channelId
     */
	#[\JMS\Serializer\Annotation\SerializedName('channel_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $channelId;
    
    /**
     * The team to be removed from the channel. Currently only a single team id can be specified.
     * 
     * @var ?string $leavingTeamIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('leaving_team_ids')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $leavingTeamIds = null;
    
	public function __construct()
	{
		$this->channelId = "";
		$this->leavingTeamIds = null;
	}
}
