<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class AdminUsergroupsListChannelsRequest
{
    /**
     * Flag to include or exclude the count of members per channel.
     * 
     * @var ?bool $includeNumMembers
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include_num_members')]
    public ?bool $includeNumMembers = null;
    
    /**
     * ID of the the workspace.
     * 
     * @var ?string $teamId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=team_id')]
    public ?string $teamId = null;
    
    /**
     * Authentication token. Requires scope: `admin.usergroups:read`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=token')]
    public string $token;
    
    /**
     * ID of the IDP group to list default channels for.
     * 
     * @var string $usergroupId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=usergroup_id')]
    public string $usergroupId;
    
	public function __construct()
	{
		$this->includeNumMembers = null;
		$this->teamId = null;
		$this->token = "";
		$this->usergroupId = "";
	}
}
