<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminUsersAssignApplicationJSON
{
    /**
     * Comma separated values of channel IDs to add user in the new workspace.
     * 
     * @var ?string $channelIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('channel_ids')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $channelIds = null;
    
    /**
     * True if user should be added to the workspace as a guest.
     * 
     * @var ?bool $isRestricted
     */
	#[\JMS\Serializer\Annotation\SerializedName('is_restricted')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isRestricted = null;
    
    /**
     * True if user should be added to the workspace as a single-channel guest.
     * 
     * @var ?bool $isUltraRestricted
     */
	#[\JMS\Serializer\Annotation\SerializedName('is_ultra_restricted')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isUltraRestricted = null;
    
    /**
     * The ID (`T1234`) of the workspace.
     * 
     * @var string $teamId
     */
	#[\JMS\Serializer\Annotation\SerializedName('team_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $teamId;
    
    /**
     * The ID of the user to add to the workspace.
     * 
     * @var string $userId
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $userId;
    
	public function __construct()
	{
		$this->channelIds = null;
		$this->isRestricted = null;
		$this->isUltraRestricted = null;
		$this->teamId = "";
		$this->userId = "";
	}
}
