<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminInviteRequestsDenyApplicationJSON
{
    /**
     * ID of the request to invite.
     * 
     * @var string $inviteRequestId
     */
	#[\JMS\Serializer\Annotation\SerializedName('invite_request_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $inviteRequestId;
    
    /**
     * ID for the workspace where the invite request was made.
     * 
     * @var ?string $teamId
     */
	#[\JMS\Serializer\Annotation\SerializedName('team_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $teamId = null;
    
	public function __construct()
	{
		$this->inviteRequestId = "";
		$this->teamId = null;
	}
}
