<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminUsergroupsAddChannelsApplicationJSON
{
    /**
     * Comma separated string of channel IDs.
     * 
     * @var string $channelIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('channel_ids')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $channelIds;
    
    /**
     * The workspace to add default channels in.
     * 
     * @var ?string $teamId
     */
	#[\JMS\Serializer\Annotation\SerializedName('team_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $teamId = null;
    
    /**
     * ID of the IDP group to add default channels for.
     * 
     * @var string $usergroupId
     */
	#[\JMS\Serializer\Annotation\SerializedName('usergroup_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $usergroupId;
    
	public function __construct()
	{
		$this->channelIds = "";
		$this->teamId = null;
		$this->usergroupId = "";
	}
}
