<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class AdminTeamsSettingsSetIconRequestBody
{
    /**
     * Image URL for the icon
     * 
     * @var string $imageUrl
     */
	#[SpeakeasyMetadata('form:name=image_url')]
    public string $imageUrl;
    
    /**
     * ID for the workspace to set the icon for.
     * 
     * @var string $teamId
     */
	#[SpeakeasyMetadata('form:name=team_id')]
    public string $teamId;
    
    /**
     * Authentication token. Requires scope: `admin.teams:write`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('form:name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->imageUrl = "";
		$this->teamId = "";
		$this->token = "";
	}
}
