<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class AdminConversationsGetTeamsRequest
{
    /**
     * The channel to determine connected workspaces within the organization for.
     * 
     * @var string $channelId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=channel_id')]
    public string $channelId;
    
    /**
     * Set `cursor` to `next_cursor` returned by the previous call to list items in the next page
     * 
     * @var ?string $cursor
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;
    
    /**
     * The maximum number of items to return. Must be between 1 - 1000 both inclusive.
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * Authentication token. Requires scope: `admin.conversations:read`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->channelId = "";
		$this->cursor = null;
		$this->limit = null;
		$this->token = "";
	}
}
