<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminUsergroupsRemoveChannelsApplicationJSON
{
    /**
     * Comma-separated string of channel IDs
     * 
     * @var string $channelIds
     */
	#[\JMS\Serializer\Annotation\SerializedName('channel_ids')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $channelIds;
    
    /**
     * ID of the IDP Group
     * 
     * @var string $usergroupId
     */
	#[\JMS\Serializer\Annotation\SerializedName('usergroup_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $usergroupId;
    
	public function __construct()
	{
		$this->channelIds = "";
		$this->usergroupId = "";
	}
}
