<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class AdminConversationsEkmListOriginalConnectedChannelInfoRequest
{
    /**
     * A comma-separated list of channels to filter to.
     * 
     * @var ?string $channelIds
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=channel_ids')]
    public ?string $channelIds = null;
    
    /**
     * Set `cursor` to `next_cursor` returned by the previous call to list items in the next page.
     * 
     * @var ?string $cursor
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;
    
    /**
     * The maximum number of items to return. Must be between 1 - 1000 both inclusive.
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * A comma-separated list of the workspaces to which the channels you would like returned belong.
     * 
     * @var ?string $teamIds
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=team_ids')]
    public ?string $teamIds = null;
    
    /**
     * Authentication token. Requires scope: `admin.conversations:read`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->channelIds = null;
		$this->cursor = null;
		$this->limit = null;
		$this->teamIds = null;
		$this->token = "";
	}
}
