<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AdminUsersSetExpirationApplicationJSON
{
    /**
     * Timestamp when guest account should be disabled.
     * 
     * @var int $expirationTs
     */
	#[\JMS\Serializer\Annotation\SerializedName('expiration_ts')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $expirationTs;
    
    /**
     * The ID (`T1234`) of the workspace.
     * 
     * @var string $teamId
     */
	#[\JMS\Serializer\Annotation\SerializedName('team_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $teamId;
    
    /**
     * The ID of the user to set an expiration for.
     * 
     * @var string $userId
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $userId;
    
	public function __construct()
	{
		$this->expirationTs = 0;
		$this->teamId = "";
		$this->userId = "";
	}
}
