<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class ApiTestRequest
{
    /**
     * Error response to return
     * 
     * @var ?string $error
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=error')]
    public ?string $error = null;
    
    /**
     * example property to return
     * 
     * @var ?string $foo
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=foo')]
    public ?string $foo = null;
    
	public function __construct()
	{
		$this->error = null;
		$this->foo = null;
	}
}
