<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AppsPermissionsResourcesListResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response
     * 
     * @var ?array<string, array<string, mixed>> $appsPermissionsResourcesListErrorSchema
     */
	
    public ?array $appsPermissionsResourcesListErrorSchema = null;
    
    /**
     * Typical successful paginated response
     * 
     * @var ?array<string, array<string, mixed>> $appsPermissionsResourcesListSuccessSchema
     */
	
    public ?array $appsPermissionsResourcesListSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->appsPermissionsResourcesListErrorSchema = null;
		$this->appsPermissionsResourcesListSuccessSchema = null;
	}
}
