<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AppsPermissionsRequestResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Standard failure response when trigger_id is invalid
     * 
     * @var ?array<string, array<string, mixed>> $appsPermissionsRequestErrorSchema
     */
	
    public ?array $appsPermissionsRequestErrorSchema = null;
    
    /**
     * Standard success response when used with a user token
     * 
     * @var ?array<string, array<string, mixed>> $appsPermissionsRequestSchema
     */
	
    public ?array $appsPermissionsRequestSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->appsPermissionsRequestErrorSchema = null;
		$this->appsPermissionsRequestSchema = null;
	}
}
