<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class AppsPermissionsRequestRequest
{
    /**
     * A comma separated list of scopes to request for
     * 
     * @var string $scopes
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=scopes')]
    public string $scopes;
    
    /**
     * Authentication token. Requires scope: `none`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public string $token;
    
    /**
     * Token used to trigger the permissions API
     * 
     * @var string $triggerId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=trigger_id')]
    public string $triggerId;
    
	public function __construct()
	{
		$this->scopes = "";
		$this->token = "";
		$this->triggerId = "";
	}
}
