<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class AppsUninstallRequest
{
    /**
     * Issued when you created your application.
     * 
     * @var ?string $clientId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=client_id')]
    public ?string $clientId = null;
    
    /**
     * Issued when you created your application.
     * 
     * @var ?string $clientSecret
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=client_secret')]
    public ?string $clientSecret = null;
    
    /**
     * Authentication token. Requires scope: `none`
     * 
     * @var ?string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public ?string $token = null;
    
	public function __construct()
	{
		$this->clientId = null;
		$this->clientSecret = null;
		$this->token = null;
	}
}
