<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class AuthRevokeRequest
{
    /**
     * Setting this parameter to `1` triggers a _testing mode_ where the specified token will not actually be revoked.
     * 
     * @var ?bool $test
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=test')]
    public ?bool $test = null;
    
    /**
     * Authentication token. Requires scope: `none`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->test = null;
		$this->token = "";
	}
}
