<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class AuthTestResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Standard failure response when used with an invalid token
     * 
     * @var ?array<string, array<string, mixed>> $authTestErrorSchema
     */
	
    public ?array $authTestErrorSchema = null;
    
    /**
     * Standard success response when used with a user token
     * 
     * @var ?array<string, array<string, mixed>> $authTestSuccessSchema
     */
	
    public ?array $authTestSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->authTestErrorSchema = null;
		$this->authTestSuccessSchema = null;
	}
}
