<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class BotsInfoResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * When no bot can be found, it returns an error.
     * 
     * @var ?array<string, array<string, mixed>> $botsInfoErrorSchema
     */
	
    public ?array $botsInfoErrorSchema = null;
    
    /**
     * When successful, returns bot info by bot ID.
     * 
     * @var ?array<string, array<string, mixed>> $botsInfoSchema
     */
	
    public ?array $botsInfoSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->botsInfoErrorSchema = null;
		$this->botsInfoSchema = null;
	}
}
