<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class CallsAddApplicationJSON
{
    /**
     * The valid Slack user ID of the user who created this Call. When this method is called with a user token, the `created_by` field is optional and defaults to the authed user of the token. Otherwise, the field is required.
     * 
     * @var ?string $createdBy
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_by')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $createdBy = null;
    
    /**
     * Call start time in UTC UNIX timestamp format
     * 
     * @var ?int $dateStart
     */
	#[\JMS\Serializer\Annotation\SerializedName('date_start')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $dateStart = null;
    
    /**
     * When supplied, available Slack clients will attempt to directly launch the 3rd-party Call with this URL.
     * 
     * @var ?string $desktopAppJoinUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('desktop_app_join_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $desktopAppJoinUrl = null;
    
    /**
     * An optional, human-readable ID supplied by the 3rd-party Call provider. If supplied, this ID will be displayed in the Call object.
     * 
     * @var ?string $externalDisplayId
     */
	#[\JMS\Serializer\Annotation\SerializedName('external_display_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $externalDisplayId = null;
    
    /**
     * An ID supplied by the 3rd-party Call provider. It must be unique across all Calls from that service.
     * 
     * @var string $externalUniqueId
     */
	#[\JMS\Serializer\Annotation\SerializedName('external_unique_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $externalUniqueId;
    
    /**
     * The URL required for a client to join the Call.
     * 
     * @var string $joinUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('join_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $joinUrl;
    
    /**
     * The name of the Call.
     * 
     * @var ?string $title
     */
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title = null;
    
    /**
     * The list of users to register as participants in the Call. [Read more on how to specify users here](/apis/calls#users).
     * 
     * @var ?string $users
     */
	#[\JMS\Serializer\Annotation\SerializedName('users')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $users = null;
    
	public function __construct()
	{
		$this->createdBy = null;
		$this->dateStart = null;
		$this->desktopAppJoinUrl = null;
		$this->externalDisplayId = null;
		$this->externalUniqueId = "";
		$this->joinUrl = "";
		$this->title = null;
		$this->users = null;
	}
}
