<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class CallsInfoRequest
{
    /**
     * `id` of the Call returned by the [`calls.add`](/methods/calls.add) method.
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=id')]
    public string $id;
    
    /**
     * Authentication token. Requires scope: `calls:read`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->id = "";
		$this->token = "";
	}
}
