<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ChatScheduleMessageResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response if the `post_at` is invalid (ex. in the past or too far into the future)
     * 
     * @var ?array<string, array<string, mixed>> $chatScheduleMessageErrorSchema
     */
	
    public ?array $chatScheduleMessageErrorSchema = null;
    
    /**
     * Typical success response
     * 
     * @var ?array<string, array<string, mixed>> $chatScheduleMessageSuccessSchema
     */
	
    public ?array $chatScheduleMessageSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->chatScheduleMessageErrorSchema = null;
		$this->chatScheduleMessageSuccessSchema = null;
	}
}
