<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ChatGetPermalinkResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response when channel cannot be found
     * 
     * @var ?array<string, array<string, mixed>> $chatGetPermalinkErrorSchema
     */
	
    public ?array $chatGetPermalinkErrorSchema = null;
    
    /**
     * Standard success response
     * 
     * @var ?array<string, array<string, mixed>> $chatGetPermalinkSuccessSchema
     */
	
    public ?array $chatGetPermalinkSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->chatGetPermalinkErrorSchema = null;
		$this->chatGetPermalinkSuccessSchema = null;
	}
}
