<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ChatUnfurlApplicationJSON
{
    /**
     * Channel ID of the message
     * 
     * @var string $channel
     */
	#[\JMS\Serializer\Annotation\SerializedName('channel')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $channel;
    
    /**
     * Timestamp of the message to add unfurl behavior to.
     * 
     * @var string $ts
     */
	#[\JMS\Serializer\Annotation\SerializedName('ts')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $ts;
    
    /**
     * URL-encoded JSON map with keys set to URLs featured in the the message, pointing to their unfurl blocks or message attachments.
     * 
     * @var ?string $unfurls
     */
	#[\JMS\Serializer\Annotation\SerializedName('unfurls')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $unfurls = null;
    
    /**
     * Provide a simply-formatted string to send as an ephemeral message to the user as invitation to authenticate further and enable full unfurling behavior
     * 
     * @var ?string $userAuthMessage
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_auth_message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $userAuthMessage = null;
    
    /**
     * Set to `true` or `1` to indicate the user must install your Slack app to trigger unfurls for this domain
     * 
     * @var ?bool $userAuthRequired
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_auth_required')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $userAuthRequired = null;
    
    /**
     * Send users to this custom URL where they will complete authentication in your app to fully trigger unfurling. Value should be properly URL-encoded.
     * 
     * @var ?string $userAuthUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('user_auth_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $userAuthUrl = null;
    
	public function __construct()
	{
		$this->channel = "";
		$this->ts = "";
		$this->unfurls = null;
		$this->userAuthMessage = null;
		$this->userAuthRequired = null;
		$this->userAuthUrl = null;
	}
}
