<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class ChatScheduledMessagesListRequest
{
    /**
     * The channel of the scheduled messages
     * 
     * @var ?string $channel
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=channel')]
    public ?string $channel = null;
    
    /**
     * For pagination purposes, this is the `cursor` value returned from a previous call to `chat.scheduledmessages.list` indicating where you want to start this call from.
     * 
     * @var ?string $cursor
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;
    
    /**
     * A UNIX timestamp of the latest value in the time range
     * 
     * @var ?float $latest
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=latest')]
    public ?float $latest = null;
    
    /**
     * Maximum number of original entries to return.
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * A UNIX timestamp of the oldest value in the time range
     * 
     * @var ?float $oldest
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=oldest')]
    public ?float $oldest = null;
    
    /**
     * Authentication token. Requires scope: `none`
     * 
     * @var ?string $token
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=token')]
    public ?string $token = null;
    
	public function __construct()
	{
		$this->channel = null;
		$this->cursor = null;
		$this->latest = null;
		$this->limit = null;
		$this->oldest = null;
		$this->token = null;
	}
}
