<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ChatPostEphemeralApplicationJSON
{
    /**
     * Pass true to post the message as the authed user. Defaults to true if the chat:write:bot scope is not included. Otherwise, defaults to false.
     * 
     * @var ?bool $asUser
     */
	#[\JMS\Serializer\Annotation\SerializedName('as_user')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $asUser = null;
    
    /**
     * A JSON-based array of structured attachments, presented as a URL-encoded string.
     * 
     * @var ?string $attachments
     */
	#[\JMS\Serializer\Annotation\SerializedName('attachments')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $attachments = null;
    
    /**
     * A JSON-based array of structured blocks, presented as a URL-encoded string.
     * 
     * @var ?string $blocks
     */
	#[\JMS\Serializer\Annotation\SerializedName('blocks')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $blocks = null;
    
    /**
     * Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name.
     * 
     * @var string $channel
     */
	#[\JMS\Serializer\Annotation\SerializedName('channel')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $channel;
    
    /**
     * Emoji to use as the icon for this message. Overrides `icon_url`. Must be used in conjunction with `as_user` set to `false`, otherwise ignored. See [authorship](#authorship) below.
     * 
     * @var ?string $iconEmoji
     */
	#[\JMS\Serializer\Annotation\SerializedName('icon_emoji')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $iconEmoji = null;
    
    /**
     * URL to an image to use as the icon for this message. Must be used in conjunction with `as_user` set to false, otherwise ignored. See [authorship](#authorship) below.
     * 
     * @var ?string $iconUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('icon_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $iconUrl = null;
    
    /**
     * Find and link channel names and usernames.
     * 
     * @var ?bool $linkNames
     */
	#[\JMS\Serializer\Annotation\SerializedName('link_names')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $linkNames = null;
    
    /**
     * Change how messages are treated. Defaults to `none`. See [below](#formatting).
     * 
     * @var ?string $parse
     */
	#[\JMS\Serializer\Annotation\SerializedName('parse')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $parse = null;
    
    /**
     * How this field works and whether it is required depends on other fields you use in your API call. [See below](#text_usage) for more detail.
     * 
     * @var ?string $text
     */
	#[\JMS\Serializer\Annotation\SerializedName('text')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $text = null;
    
    /**
     * Provide another message's `ts` value to post this message in a thread. Avoid using a reply's `ts` value; use its parent's value instead. Ephemeral messages in threads are only shown if there is already an active thread.
     * 
     * @var ?string $threadTs
     */
	#[\JMS\Serializer\Annotation\SerializedName('thread_ts')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $threadTs = null;
    
    /**
     * `id` of the user who will receive the ephemeral message. The user should be in the channel specified by the `channel` argument.
     * 
     * @var string $user
     */
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $user;
    
    /**
     * Set your bot's user name. Must be used in conjunction with `as_user` set to false, otherwise ignored. See [authorship](#authorship) below.
     * 
     * @var ?string $username
     */
	#[\JMS\Serializer\Annotation\SerializedName('username')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $username = null;
    
	public function __construct()
	{
		$this->asUser = null;
		$this->attachments = null;
		$this->blocks = null;
		$this->channel = "";
		$this->iconEmoji = null;
		$this->iconUrl = null;
		$this->linkNames = null;
		$this->parse = null;
		$this->text = null;
		$this->threadTs = null;
		$this->user = "";
		$this->username = null;
	}
}
