<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ChatDeleteScheduledMessageResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response if no message is found
     * 
     * @var ?array<string, array<string, mixed>> $chatDeleteScheduledMessageErrorSchema
     */
	
    public ?array $chatDeleteScheduledMessageErrorSchema = null;
    
    /**
     * Typical success response
     * 
     * @var ?array<string, array<string, mixed>> $chatDeleteScheduledMessageSchema
     */
	
    public ?array $chatDeleteScheduledMessageSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->chatDeleteScheduledMessageErrorSchema = null;
		$this->chatDeleteScheduledMessageSchema = null;
	}
}
