<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ChatDeleteScheduledMessageApplicationJSON
{
    /**
     * Pass true to delete the message as the authed user with `chat:write:user` scope. [Bot users](/bot-users) in this context are considered authed users. If unused or false, the message will be deleted with `chat:write:bot` scope.
     * 
     * @var ?bool $asUser
     */
	#[\JMS\Serializer\Annotation\SerializedName('as_user')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $asUser = null;
    
    /**
     * The channel the scheduled_message is posting to
     * 
     * @var string $channel
     */
	#[\JMS\Serializer\Annotation\SerializedName('channel')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $channel;
    
    /**
     * `scheduled_message_id` returned from call to chat.scheduleMessage
     * 
     * @var string $scheduledMessageId
     */
	#[\JMS\Serializer\Annotation\SerializedName('scheduled_message_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $scheduledMessageId;
    
	public function __construct()
	{
		$this->asUser = null;
		$this->channel = "";
		$this->scheduledMessageId = "";
	}
}
