<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ConversationsKickResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response when you attempt to kick yourself from a channel
     * 
     * @var ?array<string, array<string, mixed>> $conversationsKickErrorSchema
     */
	
    public ?array $conversationsKickErrorSchema = null;
    
    /**
     * Typical success response
     * 
     * @var ?array<string, array<string, mixed>> $conversationsKickSuccessSchema
     */
	
    public ?array $conversationsKickSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->conversationsKickErrorSchema = null;
		$this->conversationsKickSuccessSchema = null;
	}
}
