<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ConversationsLeaveResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response when attempting to leave a workspace's "general" channel
     * 
     * @var ?array<string, array<string, mixed>> $conversationsLeaveErrorSchema
     */
	
    public ?array $conversationsLeaveErrorSchema = null;
    
    /**
     * Typical success response
     * 
     * @var ?array<string, array<string, mixed>> $conversationsLeaveSuccessSchema
     */
	
    public ?array $conversationsLeaveSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->conversationsLeaveErrorSchema = null;
		$this->conversationsLeaveSuccessSchema = null;
	}
}
