<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ConversationsSetTopicApplicationJSON
{
    /**
     * Conversation to set the topic of
     * 
     * @var ?string $channel
     */
	#[\JMS\Serializer\Annotation\SerializedName('channel')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $channel = null;
    
    /**
     * The new topic string. Does not support formatting or linkification.
     * 
     * @var ?string $topic
     */
	#[\JMS\Serializer\Annotation\SerializedName('topic')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $topic = null;
    
	public function __construct()
	{
		$this->channel = null;
		$this->topic = null;
	}
}
