<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ConversationsJoinResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response if the conversation is archived and cannot be joined
     * 
     * @var ?array<string, array<string, mixed>> $conversationsJoinErrorSchema
     */
	
    public ?array $conversationsJoinErrorSchema = null;
    
    /**
     * Typical success response
     * 
     * @var ?array<string, array<string, mixed>> $conversationsJoinSuccessSchema
     */
	
    public ?array $conversationsJoinSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->conversationsJoinErrorSchema = null;
		$this->conversationsJoinSuccessSchema = null;
	}
}
