<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ConversationsListResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response
     * 
     * @var ?array<string, array<string, mixed>> $conversationsListErrorSchema
     */
	
    public ?array $conversationsListErrorSchema = null;
    
    /**
     * Typical success response with only public channels
     * 
     * @var ?array<string, array<string, mixed>> $conversationsListSuccessSchema
     */
	
    public ?array $conversationsListSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->conversationsListErrorSchema = null;
		$this->conversationsListSuccessSchema = null;
	}
}
