<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ConversationsHistoryResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response
     * 
     * @var ?array<string, array<string, mixed>> $conversationsHistoryErrorSchema
     */
	
    public ?array $conversationsHistoryErrorSchema = null;
    
    /**
     * Typical success response containing a channel's messages
     * 
     * @var ?array<string, array<string, mixed>> $conversationsHistorySuccessSchema
     */
	
    public ?array $conversationsHistorySuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->conversationsHistoryErrorSchema = null;
		$this->conversationsHistorySuccessSchema = null;
	}
}
