<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ConversationsCreateResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response when name already in use
     * 
     * @var ?array<string, array<string, mixed>> $conversationsCreateErrorSchema
     */
	
    public ?array $conversationsCreateErrorSchema = null;
    
    /**
     * If successful, the command returns a rather stark [conversation object](/types/conversation)
     * 
     * @var ?array<string, array<string, mixed>> $conversationsCreateSuccessSchema
     */
	
    public ?array $conversationsCreateSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->conversationsCreateErrorSchema = null;
		$this->conversationsCreateSuccessSchema = null;
	}
}
