<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class ConversationsMembersResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response when an invalid cursor is provided
     * 
     * @var ?array<string, array<string, mixed>> $conversationsMembersErrorSchema
     */
	
    public ?array $conversationsMembersErrorSchema = null;
    
    /**
     * Typical paginated success response
     * 
     * @var ?array<string, array<string, mixed>> $conversationsMembersSuccessSchema
     */
	
    public ?array $conversationsMembersSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->conversationsMembersErrorSchema = null;
		$this->conversationsMembersSuccessSchema = null;
	}
}
