<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class ConversationsListRequest
{
    /**
     * Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first "page" of the collection. See [pagination](/docs/pagination) for more detail.
     * 
     * @var ?string $cursor
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;
    
    /**
     * Set to `true` to exclude archived channels from the list
     * 
     * @var ?bool $excludeArchived
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=exclude_archived')]
    public ?bool $excludeArchived = null;
    
    /**
     * The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached. Must be an integer no larger than 1000.
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * Authentication token. Requires scope: `conversations:read`
     * 
     * @var ?string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public ?string $token = null;
    
    /**
     * Mix and match channel types by providing a comma-separated list of any combination of `public_channel`, `private_channel`, `mpim`, `im`
     * 
     * @var ?string $types
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=types')]
    public ?string $types = null;
    
	public function __construct()
	{
		$this->cursor = null;
		$this->excludeArchived = null;
		$this->limit = null;
		$this->token = null;
		$this->types = null;
	}
}
