<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class DialogOpenRequest
{
    /**
     * The dialog definition. This must be a JSON-encoded string.
     * 
     * @var string $dialog
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=dialog')]
    public string $dialog;
    
    /**
     * Authentication token. Requires scope: `none`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=token')]
    public string $token;
    
    /**
     * Exchange a trigger to post to the user.
     * 
     * @var string $triggerId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=trigger_id')]
    public string $triggerId;
    
	public function __construct()
	{
		$this->dialog = "";
		$this->token = "";
		$this->triggerId = "";
	}
}
