<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class DndTeamInfoRequest
{
    /**
     * Authentication token. Requires scope: `dnd:read`
     * 
     * @var ?string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public ?string $token = null;
    
    /**
     * Comma-separated list of users to fetch Do Not Disturb status for
     * 
     * @var ?string $users
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=users')]
    public ?string $users = null;
    
	public function __construct()
	{
		$this->token = null;
		$this->users = null;
	}
}
