<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class FilesRemoteShareRequest
{
    /**
     * Comma-separated list of channel IDs where the file will be shared.
     * 
     * @var ?string $channels
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=channels')]
    public ?string $channels = null;
    
    /**
     * The globally unique identifier (GUID) for the file, as set by the app registering the file with Slack.  Either this field or `file` or both are required.
     * 
     * @var ?string $externalId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=external_id')]
    public ?string $externalId = null;
    
    /**
     * Specify a file registered with Slack by providing its ID. Either this field or `external_id` or both are required.
     * 
     * @var ?string $file
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=file')]
    public ?string $file = null;
    
    /**
     * Authentication token. Requires scope: `remote_files:share`
     * 
     * @var ?string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public ?string $token = null;
    
	public function __construct()
	{
		$this->channels = null;
		$this->externalId = null;
		$this->file = null;
		$this->token = null;
	}
}
