<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class FilesListRequest
{
    /**
     * Filter files appearing in a specific channel, indicated by its ID.
     * 
     * @var ?string $channel
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=channel')]
    public ?string $channel = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=count')]
    public ?string $count = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?string $page = null;
    
    /**
     * Show truncated file info for files hidden due to being too old, and the team who owns the file being over the file limit.
     * 
     * @var ?bool $showFilesHiddenByLimit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=show_files_hidden_by_limit')]
    public ?bool $showFilesHiddenByLimit = null;
    
    /**
     * Authentication token. Requires scope: `files:read`
     * 
     * @var ?string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public ?string $token = null;
    
    /**
     * Filter files created after this timestamp (inclusive).
     * 
     * @var ?float $tsFrom
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ts_from')]
    public ?float $tsFrom = null;
    
    /**
     * Filter files created before this timestamp (inclusive).
     * 
     * @var ?float $tsTo
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ts_to')]
    public ?float $tsTo = null;
    
    /**
     * Filter files by type ([see below](#file_types)). You can pass multiple values in the types argument, like `types=spaces,snippets`.The default value is `all`, which does not filter the list.
     * 
     * @var ?string $types
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=types')]
    public ?string $types = null;
    
    /**
     * Filter files created by a single user.
     * 
     * @var ?string $user
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user')]
    public ?string $user = null;
    
	public function __construct()
	{
		$this->channel = null;
		$this->count = null;
		$this->page = null;
		$this->showFilesHiddenByLimit = null;
		$this->token = null;
		$this->tsFrom = null;
		$this->tsTo = null;
		$this->types = null;
		$this->user = null;
	}
}
