<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class FilesRemoteInfoRequest
{
    /**
     * Creator defined GUID for the file.
     * 
     * @var ?string $externalId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=external_id')]
    public ?string $externalId = null;
    
    /**
     * Specify a file by providing its ID.
     * 
     * @var ?string $file
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=file')]
    public ?string $file = null;
    
    /**
     * Authentication token. Requires scope: `remote_files:read`
     * 
     * @var ?string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public ?string $token = null;
    
	public function __construct()
	{
		$this->externalId = null;
		$this->file = null;
		$this->token = null;
	}
}
