<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class FilesCommentsDeleteResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Standard failure response when used with an invalid token
     * 
     * @var ?array<string, array<string, mixed>> $filesCommentsDeleteErrorSchema
     */
	
    public ?array $filesCommentsDeleteErrorSchema = null;
    
    /**
     * Standard success response is very simple
     * 
     * @var ?array<string, array<string, mixed>> $filesCommentsDeleteSchema
     */
	
    public ?array $filesCommentsDeleteSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->filesCommentsDeleteErrorSchema = null;
		$this->filesCommentsDeleteSchema = null;
	}
}
