<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class FilesRemoteAddRequestBody
{
    /**
     * Creator defined GUID for the file.
     * 
     * @var ?string $externalId
     */
	#[SpeakeasyMetadata('form:name=external_id')]
    public ?string $externalId = null;
    
    /**
     * URL of the remote file.
     * 
     * @var ?string $externalUrl
     */
	#[SpeakeasyMetadata('form:name=external_url')]
    public ?string $externalUrl = null;
    
    /**
     * type of file
     * 
     * @var ?string $filetype
     */
	#[SpeakeasyMetadata('form:name=filetype')]
    public ?string $filetype = null;
    
    /**
     * A text file (txt, pdf, doc, etc.) containing textual search terms that are used to improve discovery of the remote file.
     * 
     * @var ?string $indexableFileContents
     */
	#[SpeakeasyMetadata('form:name=indexable_file_contents')]
    public ?string $indexableFileContents = null;
    
    /**
     * Preview of the document via `multipart/form-data`.
     * 
     * @var ?string $previewImage
     */
	#[SpeakeasyMetadata('form:name=preview_image')]
    public ?string $previewImage = null;
    
    /**
     * Title of the file being shared.
     * 
     * @var ?string $title
     */
	#[SpeakeasyMetadata('form:name=title')]
    public ?string $title = null;
    
    /**
     * Authentication token. Requires scope: `remote_files:write`
     * 
     * @var ?string $token
     */
	#[SpeakeasyMetadata('form:name=token')]
    public ?string $token = null;
    
	public function __construct()
	{
		$this->externalId = null;
		$this->externalUrl = null;
		$this->filetype = null;
		$this->indexableFileContents = null;
		$this->previewImage = null;
		$this->title = null;
		$this->token = null;
	}
}
