<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class OauthTokenRequest
{
    /**
     * Issued when you created your application.
     * 
     * @var ?string $clientId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=client_id')]
    public ?string $clientId = null;
    
    /**
     * Issued when you created your application.
     * 
     * @var ?string $clientSecret
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=client_secret')]
    public ?string $clientSecret = null;
    
    /**
     * The `code` param returned via the OAuth callback.
     * 
     * @var ?string $code
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=code')]
    public ?string $code = null;
    
    /**
     * This must match the originally submitted URI (if one was sent).
     * 
     * @var ?string $redirectUri
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=redirect_uri')]
    public ?string $redirectUri = null;
    
    /**
     * Request the user to add your app only to a single channel.
     * 
     * @var ?bool $singleChannel
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=single_channel')]
    public ?bool $singleChannel = null;
    
	public function __construct()
	{
		$this->clientId = null;
		$this->clientSecret = null;
		$this->code = null;
		$this->redirectUri = null;
		$this->singleChannel = null;
	}
}
