<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class PinsListResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response
     * 
     * @var ?array<string, array<string, mixed>> $pinsListErrorSchema
     */
	
    public ?array $pinsListErrorSchema = null;
    
    /**
     * Typical success response
     * 
     * @var ?array<string, mixed> $pinsListSuccessSchema
     */
	
    public ?array $pinsListSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->pinsListErrorSchema = null;
		$this->pinsListSuccessSchema = null;
	}
}
