<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class RtmConnectRequest
{
    /**
     * Batch presence deliveries via subscription. Enabling changes the shape of `presence_change` events. See [batch presence](/docs/presence-and-status#batching).
     * 
     * @var ?bool $batchPresenceAware
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=batch_presence_aware')]
    public ?bool $batchPresenceAware = null;
    
    /**
     * Only deliver presence events when requested by subscription. See [presence subscriptions](/docs/presence-and-status#subscriptions).
     * 
     * @var ?bool $presenceSub
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=presence_sub')]
    public ?bool $presenceSub = null;
    
    /**
     * Authentication token. Requires scope: `rtm:stream`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->batchPresenceAware = null;
		$this->presenceSub = null;
		$this->token = "";
	}
}
