<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class TeamInfoRequest
{
    /**
     * Team to get info on, if omitted, will return information about the current team. Will only return team that the authenticated token is allowed to see through external shared channels
     * 
     * @var ?string $team
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=team')]
    public ?string $team = null;
    
    /**
     * Authentication token. Requires scope: `team:read`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->team = null;
		$this->token = "";
	}
}
