<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class TeamIntegrationLogsRequest
{
    /**
     * Filter logs to this Slack app. Defaults to all logs.
     * 
     * @var ?string $appId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=app_id')]
    public ?string $appId = null;
    
    /**
     * Filter logs with this change type. Defaults to all logs.
     * 
     * @var ?string $changeType
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=change_type')]
    public ?string $changeType = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=count')]
    public ?string $count = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?string $page = null;
    
    /**
     * Filter logs to this service. Defaults to all logs.
     * 
     * @var ?string $serviceId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=service_id')]
    public ?string $serviceId = null;
    
    /**
     * Authentication token. Requires scope: `admin`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public string $token;
    
    /**
     * Filter logs generated by this user’s actions. Defaults to all logs.
     * 
     * @var ?string $user
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user')]
    public ?string $user = null;
    
	public function __construct()
	{
		$this->appId = null;
		$this->changeType = null;
		$this->count = null;
		$this->page = null;
		$this->serviceId = null;
		$this->token = "";
		$this->user = null;
	}
}
