<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class TeamIntegrationLogsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response
     * 
     * @var ?array<string, array<string, mixed>> $teamIntegrationLogsErrorSchema
     */
	
    public ?array $teamIntegrationLogsErrorSchema = null;
    
    /**
     * Typical success response
     * 
     * @var ?array<string, array<string, mixed>> $teamIntegrationLogsSchema
     */
	
    public ?array $teamIntegrationLogsSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->teamIntegrationLogsErrorSchema = null;
		$this->teamIntegrationLogsSchema = null;
	}
}
