<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class UsersIdentityResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response
     * 
     * @var ?array<string, array<string, mixed>> $usersIdentityErrorSchema
     */
	
    public ?array $usersIdentityErrorSchema = null;
    
    /**
     * You will receive at a minimum the following information:
     * 
     * @var ?array<string, mixed> $usersIdentitySchema
     */
	
    public ?array $usersIdentitySchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->usersIdentityErrorSchema = null;
		$this->usersIdentitySchema = null;
	}
}
