<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class UsersGetPresenceResponse
{
    /**
     * When requesting information for a different user, this method just returns the current presence (either `active` or `away`).
     * 
     * @var ?array<string, array<string, mixed>> $apiMethodUsersGetPresence
     */
	
    public ?array $apiMethodUsersGetPresence = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response
     * 
     * @var ?array<string, array<string, mixed>> $usersCountsErrorSchema
     */
	
    public ?array $usersCountsErrorSchema = null;
    
	public function __construct()
	{
		$this->apiMethodUsersGetPresence = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->usersCountsErrorSchema = null;
	}
}
