<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class UsergroupsCreateApplicationJSON
{
    /**
     * A comma separated string of encoded channel IDs for which the User Group uses as a default.
     * 
     * @var ?string $channels
     */
	#[\JMS\Serializer\Annotation\SerializedName('channels')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $channels = null;
    
    /**
     * A short description of the User Group.
     * 
     * @var ?string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
    /**
     * A mention handle. Must be unique among channels, users and User Groups.
     * 
     * @var ?string $handle
     */
	#[\JMS\Serializer\Annotation\SerializedName('handle')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $handle = null;
    
    /**
     * Include the number of users in each User Group.
     * 
     * @var ?bool $includeCount
     */
	#[\JMS\Serializer\Annotation\SerializedName('include_count')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $includeCount = null;
    
    /**
     * A name for the User Group. Must be unique among User Groups.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	public function __construct()
	{
		$this->channels = null;
		$this->description = null;
		$this->handle = null;
		$this->includeCount = null;
		$this->name = "";
	}
}
