<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class UsergroupsEnableApplicationJSON
{
    /**
     * Include the number of users in the User Group.
     * 
     * @var ?bool $includeCount
     */
	#[\JMS\Serializer\Annotation\SerializedName('include_count')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $includeCount = null;
    
    /**
     * The encoded ID of the User Group to enable.
     * 
     * @var string $usergroup
     */
	#[\JMS\Serializer\Annotation\SerializedName('usergroup')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $usergroup;
    
	public function __construct()
	{
		$this->includeCount = null;
		$this->usergroup = "";
	}
}
