<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class UsersDeletePhotoRequestBody
{
    /**
     * Authentication token. Requires scope: `users.profile:write`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('form:name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->token = "";
	}
}
