<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class UsersLookupByEmailRequest
{
    /**
     * An email address belonging to a user in the workspace
     * 
     * @var string $email
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=email')]
    public string $email;
    
    /**
     * Authentication token. Requires scope: `users:read.email`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=token')]
    public string $token;
    
	public function __construct()
	{
		$this->email = "";
		$this->token = "";
	}
}
