<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;


class UsersConversationsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Typical error response
     * 
     * @var ?array<string, array<string, mixed>> $usersConversationsErrorSchema
     */
	
    public ?array $usersConversationsErrorSchema = null;
    
    /**
     * Typical success response with only public channels. Note how `num_members` and `is_member` are not returned like typical `conversations` objects.
     * 
     * @var ?array<string, array<string, mixed>> $usersConversationsSuccessSchema
     */
	
    public ?array $usersConversationsSuccessSchema = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->usersConversationsErrorSchema = null;
		$this->usersConversationsSuccessSchema = null;
	}
}
