<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class ViewsPublishRequest
{
    /**
     * A string that represents view state to protect against possible race conditions.
     * 
     * @var ?string $hash
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=hash')]
    public ?string $hash = null;
    
    /**
     * Authentication token. Requires scope: `none`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=token')]
    public string $token;
    
    /**
     * `id` of the user you want publish a view to.
     * 
     * @var string $userId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user_id')]
    public string $userId;
    
    /**
     * A [view payload](/reference/surfaces/views). This must be a JSON-encoded string.
     * 
     * @var string $view
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=view')]
    public string $view;
    
	public function __construct()
	{
		$this->hash = null;
		$this->token = "";
		$this->userId = "";
		$this->view = "";
	}
}
