<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class WorkflowsUpdateStepRequest
{
    /**
     * A JSON key-value map of inputs required from a user during configuration. This is the data your app expects to receive when the workflow step starts. **Please note**: the embedded variable format is set and replaced by the workflow system. You cannot create custom variables that will be replaced at runtime. [Read more about variables in workflow steps here](/workflows/steps#variables).
     * 
     * @var ?string $inputs
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=inputs')]
    public ?string $inputs = null;
    
    /**
     * An JSON array of output objects used during step execution. This is the data your app agrees to provide when your workflow step was executed.
     * 
     * @var ?string $outputs
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=outputs')]
    public ?string $outputs = null;
    
    /**
     * An optional field that can be used to override app image that is shown in the Workflow Builder.
     * 
     * @var ?string $stepImageUrl
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=step_image_url')]
    public ?string $stepImageUrl = null;
    
    /**
     * An optional field that can be used to override the step name that is shown in the Workflow Builder.
     * 
     * @var ?string $stepName
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=step_name')]
    public ?string $stepName = null;
    
    /**
     * Authentication token. Requires scope: `workflow.steps:execute`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=token')]
    public string $token;
    
    /**
     * A context identifier provided with `view_submission` payloads used to call back to `workflows.updateStep`.
     * 
     * @var string $workflowStepEditId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=workflow_step_edit_id')]
    public string $workflowStepEditId;
    
	public function __construct()
	{
		$this->inputs = null;
		$this->outputs = null;
		$this->stepImageUrl = null;
		$this->stepName = null;
		$this->token = "";
		$this->workflowStepEditId = "";
	}
}
