<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec\Models\Operations;

use \shadowcodex\slackspec\Utils\SpeakeasyMetadata;
class WorkflowsStepCompletedRequest
{
    /**
     * Key-value object of outputs from your step. Keys of this object reflect the configured `key` properties of your [`outputs`](/reference/workflows/workflow_step#output) array from your `workflow_step` object.
     * 
     * @var ?string $outputs
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=outputs')]
    public ?string $outputs = null;
    
    /**
     * Authentication token. Requires scope: `workflow.steps:execute`
     * 
     * @var string $token
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=token')]
    public string $token;
    
    /**
     * Context identifier that maps to the correct workflow step execution.
     * 
     * @var string $workflowStepExecuteId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=workflow_step_execute_id')]
    public string $workflowStepExecuteId;
    
	public function __construct()
	{
		$this->outputs = null;
		$this->token = "";
		$this->workflowStepExecuteId = "";
	}
}
