<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec;

class AdminTeamsSettings 
{

	// SDK private variables namespaced with _ to avoid conflicts with API models
	private \GuzzleHttp\ClientInterface $_defaultClient;
	private \GuzzleHttp\ClientInterface $_securityClient;
	private string $_serverUrl;
	private string $_language;
	private string $_sdkVersion;
	private string $_genVersion;	

	/**
	 * @param \GuzzleHttp\ClientInterface $defaultClient
	 * @param \GuzzleHttp\ClientInterface $securityClient
	 * @param string $serverUrl
	 * @param string $language
	 * @param string $sdkVersion
	 * @param string $genVersion
	 */
	public function __construct(\GuzzleHttp\ClientInterface $defaultClient, \GuzzleHttp\ClientInterface $securityClient, string $serverUrl, string $language, string $sdkVersion, string $genVersion)
	{
		$this->_defaultClient = $defaultClient;
		$this->_securityClient = $securityClient;
		$this->_serverUrl = $serverUrl;
		$this->_language = $language;
		$this->_sdkVersion = $sdkVersion;
		$this->_genVersion = $genVersion;
	}
	
    /**
     * Fetch information about settings in a workspace
     * 
     * https://api.slack.com/methods/admin.teams.settings.info - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsInfoRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsInfoSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsInfoResponse
     * @see https://api.slack.com/methods/admin.teams.settings.info
     */
	
    public function adminTeamsSettingsInfo(
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsInfoRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsInfoSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsInfoResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.teams.settings.info');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsInfoRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsInfoResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Set the default channels of a workspace.
     * 
     * https://api.slack.com/methods/admin.teams.settings.setDefaultChannels - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDefaultChannelsRequestBody $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDefaultChannelsSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDefaultChannelsResponse
     * @see https://api.slack.com/methods/admin.teams.settings.setDefaultChannels
     */
	
    public function adminTeamsSettingsSetDefaultChannels(
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDefaultChannelsRequestBody $request,
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDefaultChannelsSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDefaultChannelsResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.teams.settings.setDefaultChannels');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "form");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDefaultChannelsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Set the description of a given workspace.
     * 
     * https://api.slack.com/methods/admin.teams.settings.setDescription - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDescriptionRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDescriptionSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDescriptionResponse
     * @see https://api.slack.com/methods/admin.teams.settings.setDescription
     */
	
    public function adminTeamsSettingsSetDescription(
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDescriptionRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDescriptionSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDescriptionResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.teams.settings.setDescription');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "requestBody", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDescriptionResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * An API method that allows admins to set the discoverability of a given workspace
     * 
     * https://api.slack.com/methods/admin.teams.settings.setDiscoverability - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDiscoverabilityRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDiscoverabilitySecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDiscoverabilityResponse
     * @see https://api.slack.com/methods/admin.teams.settings.setDiscoverability
     */
	
    public function adminTeamsSettingsSetDiscoverability(
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDiscoverabilityRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDiscoverabilitySecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDiscoverabilityResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.teams.settings.setDiscoverability');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "requestBody", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetDiscoverabilityResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Sets the icon of a workspace.
     * 
     * https://api.slack.com/methods/admin.teams.settings.setIcon - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetIconRequestBody $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetIconSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetIconResponse
     * @see https://api.slack.com/methods/admin.teams.settings.setIcon
     */
	
    public function adminTeamsSettingsSetIcon(
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetIconRequestBody $request,
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetIconSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetIconResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.teams.settings.setIcon');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "form");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetIconResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Set the name of a given workspace.
     * 
     * https://api.slack.com/methods/admin.teams.settings.setName - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetNameRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetNameSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetNameResponse
     * @see https://api.slack.com/methods/admin.teams.settings.setName
     */
	
    public function adminTeamsSettingsSetName(
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetNameRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetNameSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetNameResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.teams.settings.setName');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "requestBody", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminTeamsSettingsSetNameResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
}