<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec;

class AdminUsergroups 
{

	// SDK private variables namespaced with _ to avoid conflicts with API models
	private \GuzzleHttp\ClientInterface $_defaultClient;
	private \GuzzleHttp\ClientInterface $_securityClient;
	private string $_serverUrl;
	private string $_language;
	private string $_sdkVersion;
	private string $_genVersion;	

	/**
	 * @param \GuzzleHttp\ClientInterface $defaultClient
	 * @param \GuzzleHttp\ClientInterface $securityClient
	 * @param string $serverUrl
	 * @param string $language
	 * @param string $sdkVersion
	 * @param string $genVersion
	 */
	public function __construct(\GuzzleHttp\ClientInterface $defaultClient, \GuzzleHttp\ClientInterface $securityClient, string $serverUrl, string $language, string $sdkVersion, string $genVersion)
	{
		$this->_defaultClient = $defaultClient;
		$this->_securityClient = $securityClient;
		$this->_serverUrl = $serverUrl;
		$this->_language = $language;
		$this->_sdkVersion = $sdkVersion;
		$this->_genVersion = $genVersion;
	}
	
    /**
     * Add one or more default channels to an IDP group.
     * 
     * https://api.slack.com/methods/admin.usergroups.addChannels - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddChannelsRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddChannelsSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddChannelsResponse
     * @see https://api.slack.com/methods/admin.usergroups.addChannels
     */
	
    public function adminUsergroupsAddChannels(
        \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddChannelsRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddChannelsSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddChannelsResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.usergroups.addChannels');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "requestBody", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddChannelsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Associate one or more default workspaces with an organization-wide IDP group.
     * 
     * https://api.slack.com/methods/admin.usergroups.addTeams - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddTeamsRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddTeamsSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddTeamsResponse
     * @see https://api.slack.com/methods/admin.usergroups.addTeams
     */
	
    public function adminUsergroupsAddTeams(
        \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddTeamsRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddTeamsSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddTeamsResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.usergroups.addTeams');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "requestBody", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminUsergroupsAddTeamsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * List the channels linked to an org-level IDP group (user group).
     * 
     * https://api.slack.com/methods/admin.usergroups.listChannels - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminUsergroupsListChannelsRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminUsergroupsListChannelsSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminUsergroupsListChannelsResponse
     * @see https://api.slack.com/methods/admin.usergroups.listChannels
     */
	
    public function adminUsergroupsListChannels(
        \shadowcodex\slackspec\Models\Operations\AdminUsergroupsListChannelsRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminUsergroupsListChannelsSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminUsergroupsListChannelsResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.usergroups.listChannels');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\AdminUsergroupsListChannelsRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminUsergroupsListChannelsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Remove one or more default channels from an org-level IDP group (user group).
     * 
     * https://api.slack.com/methods/admin.usergroups.removeChannels - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminUsergroupsRemoveChannelsRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminUsergroupsRemoveChannelsSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminUsergroupsRemoveChannelsResponse
     * @see https://api.slack.com/methods/admin.usergroups.removeChannels
     */
	
    public function adminUsergroupsRemoveChannels(
        \shadowcodex\slackspec\Models\Operations\AdminUsergroupsRemoveChannelsRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminUsergroupsRemoveChannelsSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminUsergroupsRemoveChannelsResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.usergroups.removeChannels');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "requestBody", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminUsergroupsRemoveChannelsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
}