<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec;

class AdminEmoji 
{

	// SDK private variables namespaced with _ to avoid conflicts with API models
	private \GuzzleHttp\ClientInterface $_defaultClient;
	private \GuzzleHttp\ClientInterface $_securityClient;
	private string $_serverUrl;
	private string $_language;
	private string $_sdkVersion;
	private string $_genVersion;	

	/**
	 * @param \GuzzleHttp\ClientInterface $defaultClient
	 * @param \GuzzleHttp\ClientInterface $securityClient
	 * @param string $serverUrl
	 * @param string $language
	 * @param string $sdkVersion
	 * @param string $genVersion
	 */
	public function __construct(\GuzzleHttp\ClientInterface $defaultClient, \GuzzleHttp\ClientInterface $securityClient, string $serverUrl, string $language, string $sdkVersion, string $genVersion)
	{
		$this->_defaultClient = $defaultClient;
		$this->_securityClient = $securityClient;
		$this->_serverUrl = $serverUrl;
		$this->_language = $language;
		$this->_sdkVersion = $sdkVersion;
		$this->_genVersion = $genVersion;
	}
	
    /**
     * Add an emoji.
     * 
     * https://api.slack.com/methods/admin.emoji.add - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiAddRequestBody $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiAddSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminEmojiAddResponse
     * @see https://api.slack.com/methods/admin.emoji.add
     */
	
    public function adminEmojiAdd(
        \shadowcodex\slackspec\Models\Operations\AdminEmojiAddRequestBody $request,
        \shadowcodex\slackspec\Models\Operations\AdminEmojiAddSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminEmojiAddResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.emoji.add');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "form");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminEmojiAddResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Add an emoji alias.
     * 
     * https://api.slack.com/methods/admin.emoji.addAlias - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiAddAliasRequestBody $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiAddAliasSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminEmojiAddAliasResponse
     * @see https://api.slack.com/methods/admin.emoji.addAlias
     */
	
    public function adminEmojiAddAlias(
        \shadowcodex\slackspec\Models\Operations\AdminEmojiAddAliasRequestBody $request,
        \shadowcodex\slackspec\Models\Operations\AdminEmojiAddAliasSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminEmojiAddAliasResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.emoji.addAlias');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "form");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminEmojiAddAliasResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * List emoji for an Enterprise Grid organization.
     * 
     * https://api.slack.com/methods/admin.emoji.list - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiListRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiListSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminEmojiListResponse
     * @see https://api.slack.com/methods/admin.emoji.list
     */
	
    public function adminEmojiList(
        \shadowcodex\slackspec\Models\Operations\AdminEmojiListRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminEmojiListSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminEmojiListResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.emoji.list');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\AdminEmojiListRequest::class, $request, null));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminEmojiListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Remove an emoji across an Enterprise Grid organization
     * 
     * https://api.slack.com/methods/admin.emoji.remove - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiRemoveRequestBody $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiRemoveSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminEmojiRemoveResponse
     * @see https://api.slack.com/methods/admin.emoji.remove
     */
	
    public function adminEmojiRemove(
        \shadowcodex\slackspec\Models\Operations\AdminEmojiRemoveRequestBody $request,
        \shadowcodex\slackspec\Models\Operations\AdminEmojiRemoveSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminEmojiRemoveResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.emoji.remove');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "form");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminEmojiRemoveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Rename an emoji.
     * 
     * https://api.slack.com/methods/admin.emoji.rename - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiRenameRequestBody $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminEmojiRenameSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminEmojiRenameResponse
     * @see https://api.slack.com/methods/admin.emoji.rename
     */
	
    public function adminEmojiRename(
        \shadowcodex\slackspec\Models\Operations\AdminEmojiRenameRequestBody $request,
        \shadowcodex\slackspec\Models\Operations\AdminEmojiRenameSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminEmojiRenameResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.emoji.rename');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "form");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminEmojiRenameResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
}