<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec;

class AdminInviteRequests 
{

	// SDK private variables namespaced with _ to avoid conflicts with API models
	private \GuzzleHttp\ClientInterface $_defaultClient;
	private \GuzzleHttp\ClientInterface $_securityClient;
	private string $_serverUrl;
	private string $_language;
	private string $_sdkVersion;
	private string $_genVersion;	

	/**
	 * @param \GuzzleHttp\ClientInterface $defaultClient
	 * @param \GuzzleHttp\ClientInterface $securityClient
	 * @param string $serverUrl
	 * @param string $language
	 * @param string $sdkVersion
	 * @param string $genVersion
	 */
	public function __construct(\GuzzleHttp\ClientInterface $defaultClient, \GuzzleHttp\ClientInterface $securityClient, string $serverUrl, string $language, string $sdkVersion, string $genVersion)
	{
		$this->_defaultClient = $defaultClient;
		$this->_securityClient = $securityClient;
		$this->_serverUrl = $serverUrl;
		$this->_language = $language;
		$this->_sdkVersion = $sdkVersion;
		$this->_genVersion = $genVersion;
	}
	
    /**
     * Approve a workspace invite request.
     * 
     * https://api.slack.com/methods/admin.inviteRequests.approve - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsApproveRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsApproveSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsApproveResponse
     * @see https://api.slack.com/methods/admin.inviteRequests.approve
     */
	
    public function adminInviteRequestsApprove(
        \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsApproveRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsApproveSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsApproveResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.inviteRequests.approve');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "requestBody", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsApproveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Deny a workspace invite request.
     * 
     * https://api.slack.com/methods/admin.inviteRequests.deny - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsDenyRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsDenySecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsDenyResponse
     * @see https://api.slack.com/methods/admin.inviteRequests.deny
     */
	
    public function adminInviteRequestsDeny(
        \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsDenyRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsDenySecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsDenyResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.inviteRequests.deny');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "requestBody", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsDenyResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * List all pending workspace invite requests.
     * 
     * https://api.slack.com/methods/admin.inviteRequests.list - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsListRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsListSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsListResponse
     * @see https://api.slack.com/methods/admin.inviteRequests.list
     */
	
    public function adminInviteRequestsList(
        \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsListRequest $request,
        \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsListSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsListResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/admin.inviteRequests.list');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\AdminInviteRequestsListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\AdminInviteRequestsListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
}