<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec;

class Team 
{

	// SDK private variables namespaced with _ to avoid conflicts with API models
	private \GuzzleHttp\ClientInterface $_defaultClient;
	private \GuzzleHttp\ClientInterface $_securityClient;
	private string $_serverUrl;
	private string $_language;
	private string $_sdkVersion;
	private string $_genVersion;	

	/**
	 * @param \GuzzleHttp\ClientInterface $defaultClient
	 * @param \GuzzleHttp\ClientInterface $securityClient
	 * @param string $serverUrl
	 * @param string $language
	 * @param string $sdkVersion
	 * @param string $genVersion
	 */
	public function __construct(\GuzzleHttp\ClientInterface $defaultClient, \GuzzleHttp\ClientInterface $securityClient, string $serverUrl, string $language, string $sdkVersion, string $genVersion)
	{
		$this->_defaultClient = $defaultClient;
		$this->_securityClient = $securityClient;
		$this->_serverUrl = $serverUrl;
		$this->_language = $language;
		$this->_sdkVersion = $sdkVersion;
		$this->_genVersion = $genVersion;
	}
	
    /**
     * Gets the access logs for the current team.
     * 
     * https://api.slack.com/methods/team.accessLogs - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\TeamAccessLogsRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\TeamAccessLogsSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\TeamAccessLogsResponse
     * @see https://api.slack.com/methods/team.accessLogs
     */
	
    public function teamAccessLogs(
        \shadowcodex\slackspec\Models\Operations\TeamAccessLogsRequest $request,
        \shadowcodex\slackspec\Models\Operations\TeamAccessLogsSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\TeamAccessLogsResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/team.accessLogs');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\TeamAccessLogsRequest::class, $request, null));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\TeamAccessLogsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->teamAccessLogsSchema = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->teamAccessLogsErrorSchema = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Gets billable users information for the current team.
     * 
     * https://api.slack.com/methods/team.billableInfo - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\TeamBillableInfoRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\TeamBillableInfoSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\TeamBillableInfoResponse
     * @see https://api.slack.com/methods/team.billableInfo
     */
	
    public function teamBillableInfo(
        \shadowcodex\slackspec\Models\Operations\TeamBillableInfoRequest $request,
        \shadowcodex\slackspec\Models\Operations\TeamBillableInfoSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\TeamBillableInfoResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/team.billableInfo');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\TeamBillableInfoRequest::class, $request, null));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\TeamBillableInfoResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Gets information about the current team.
     * 
     * https://api.slack.com/methods/team.info - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\TeamInfoRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\TeamInfoSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\TeamInfoResponse
     * @see https://api.slack.com/methods/team.info
     */
	
    public function teamInfo(
        \shadowcodex\slackspec\Models\Operations\TeamInfoRequest $request,
        \shadowcodex\slackspec\Models\Operations\TeamInfoSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\TeamInfoResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/team.info');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\TeamInfoRequest::class, $request, null));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\TeamInfoResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->teamInfoSchema = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->teamInfoErrorSchema = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Gets the integration logs for the current team.
     * 
     * https://api.slack.com/methods/team.integrationLogs - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\TeamIntegrationLogsRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\TeamIntegrationLogsSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\TeamIntegrationLogsResponse
     * @see https://api.slack.com/methods/team.integrationLogs
     */
	
    public function teamIntegrationLogs(
        \shadowcodex\slackspec\Models\Operations\TeamIntegrationLogsRequest $request,
        \shadowcodex\slackspec\Models\Operations\TeamIntegrationLogsSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\TeamIntegrationLogsResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/team.integrationLogs');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\TeamIntegrationLogsRequest::class, $request, null));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\TeamIntegrationLogsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->teamIntegrationLogsSchema = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->teamIntegrationLogsErrorSchema = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Retrieve a team's profile.
     * 
     * https://api.slack.com/methods/team.profile.get - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\TeamProfileGetRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\TeamProfileGetSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\TeamProfileGetResponse
     * @see https://api.slack.com/methods/team.profile.get
     */
	
    public function teamProfileGet(
        \shadowcodex\slackspec\Models\Operations\TeamProfileGetRequest $request,
        \shadowcodex\slackspec\Models\Operations\TeamProfileGetSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\TeamProfileGetResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/team.profile.get');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\TeamProfileGetRequest::class, $request, null));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\TeamProfileGetResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->teamProfileGetSuccessSchema = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->teamProfileGetErrorSchema = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
}