<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace shadowcodex\slackspec;

class Workflows 
{

	// SDK private variables namespaced with _ to avoid conflicts with API models
	private \GuzzleHttp\ClientInterface $_defaultClient;
	private \GuzzleHttp\ClientInterface $_securityClient;
	private string $_serverUrl;
	private string $_language;
	private string $_sdkVersion;
	private string $_genVersion;	

	/**
	 * @param \GuzzleHttp\ClientInterface $defaultClient
	 * @param \GuzzleHttp\ClientInterface $securityClient
	 * @param string $serverUrl
	 * @param string $language
	 * @param string $sdkVersion
	 * @param string $genVersion
	 */
	public function __construct(\GuzzleHttp\ClientInterface $defaultClient, \GuzzleHttp\ClientInterface $securityClient, string $serverUrl, string $language, string $sdkVersion, string $genVersion)
	{
		$this->_defaultClient = $defaultClient;
		$this->_securityClient = $securityClient;
		$this->_serverUrl = $serverUrl;
		$this->_language = $language;
		$this->_sdkVersion = $sdkVersion;
		$this->_genVersion = $genVersion;
	}
	
    /**
     * Indicate that an app's step in a workflow completed execution.
     * 
     * https://api.slack.com/methods/workflows.stepCompleted - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\WorkflowsStepCompletedRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\WorkflowsStepCompletedSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\WorkflowsStepCompletedResponse
     * @see https://api.slack.com/methods/workflows.stepCompleted
     */
	
    public function workflowsStepCompleted(
        \shadowcodex\slackspec\Models\Operations\WorkflowsStepCompletedRequest $request,
        \shadowcodex\slackspec\Models\Operations\WorkflowsStepCompletedSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\WorkflowsStepCompletedResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/workflows.stepCompleted');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\WorkflowsStepCompletedRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\WorkflowsStepCompletedResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Indicate that an app's step in a workflow failed to execute.
     * 
     * https://api.slack.com/methods/workflows.stepFailed - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\WorkflowsStepFailedRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\WorkflowsStepFailedSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\WorkflowsStepFailedResponse
     * @see https://api.slack.com/methods/workflows.stepFailed
     */
	
    public function workflowsStepFailed(
        \shadowcodex\slackspec\Models\Operations\WorkflowsStepFailedRequest $request,
        \shadowcodex\slackspec\Models\Operations\WorkflowsStepFailedSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\WorkflowsStepFailedResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/workflows.stepFailed');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\WorkflowsStepFailedRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\WorkflowsStepFailedResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Update the configuration for a workflow extension step.
     * 
     * https://api.slack.com/methods/workflows.updateStep - API method documentation
     * 
     * @param \shadowcodex\slackspec\Models\Operations\WorkflowsUpdateStepRequest $request
     * @param \shadowcodex\slackspec\Models\Operations\WorkflowsUpdateStepSecurity $security
     * @return \shadowcodex\slackspec\Models\Operations\WorkflowsUpdateStepResponse
     * @see https://api.slack.com/methods/workflows.updateStep
     */
	
    public function workflowsUpdateStep(
        \shadowcodex\slackspec\Models\Operations\WorkflowsUpdateStepRequest $request,
        \shadowcodex\slackspec\Models\Operations\WorkflowsUpdateStepSecurity $security,
    ): \shadowcodex\slackspec\Models\Operations\WorkflowsUpdateStepResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/workflows.updateStep');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\shadowcodex\slackspec\Models\Operations\WorkflowsUpdateStepRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        
        $client = Utils\Utils::configureSecurityClient($this->_defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \shadowcodex\slackspec\Models\Operations\WorkflowsUpdateStepResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultSuccessTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->defaultErrorTemplate = $serializer->deserialize((string)$httpResponse->getBody(), 'array<string, array<string, mixed>>', 'json');
            }
        }

        return $response;
    }
}